name: Advanced Pipeline

on:
  push:
    branches:
      - test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
        with:
          node-version: '22'
      - name: Run tests
        run: npm test
      - name: Deploy (Simulated)
        run: echo "Despliegue completado (simulado)"
