name: SECRET Pipeline

on:
  push:
    branches:
      - test
    paths_ignore:
      - '.github/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Deploy (Simulated)
        run: echo "Despliegue completado (simulado)"
      - name: Use Deploy Key
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run:
          echo "Usando la clave de despliegue $DEPLOY_KEY"
      - name: Use URL API
        run:
          echo "La Url de la API es ${{ variable.URL_API }}"
